server: 
  port: 8080
spring: 
  application: 
    name: friendsnet
  datasource: 
    password: a
    url: jdbc:h2:~/db_friendsnet;DB_CLOSE_DELAY=1000
    username: a
  jpa: 
    hibernate: 
      ddl-auto: create-drop
  h2: 
    console: 
      enabled: true